### ISSUE TITLE
virtual function declaration breaks compile for ATtiny85 in IDE 1.0 or younger

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rjbatista/tm1638-library#29]
```
What steps will reproduce the problem?
1.Try to compile the TM1640 example for target ATtiny85 board (Arduino-Tiny 
cores)
2.Works with IDE pre-1.0 but not with any version 1.0 or younger
3.

What is the expected output? What do you see instead?
Expect compile without errors, instead get this:
TM1638\TM16XX.cpp.o:(.rodata._ZTV6TM16XX+0x14): undefined reference to 
`__cxa_pure_virtual'

What version of the product are you using? On what operating system?
Any that support TM1640 are the only ones I've tried.

Please provide any additional information below.
Discussion and remedy for the problem here:
http://arduino.cc/forum/index.php?topic=162094.new%3btopicseen#new


```

Original issue reported on code.google.com by `GeoffPSt...@gmail.com` on 22 Apr 2013 at 2:10
